#!/usr/bin/python3


# Function that Raises a name exception with a message
def raise_exception_msg(message=""):
    # To know more about exception:
    # https://www.programiz.com/python-programming/exceptions
    # Raised when a variable is not found in local or global scope.
    raise NameError(message)
